import carPic1 from "../assets/carro 1.png";
import carPic2 from "../assets/carro 2.png";
import carPic3 from "../assets/carro 3.png";

const carro1 = "../assets/carro 3.png";

export const mockList = [
  {
    imageURL: `${carPic1}`,
    Marca: "Toyota",
    Modelo: "Corolla",
    Combustível: "Gasolina",
    Cor: "Branco",
    Ano: 2018,
    Km: 35000,
    Preço: 45000,
  },
  {
    imageURL: `${carPic2}`,
    Marca: "Honda",
    Modelo: "Civic",
    Combustível: "Etanol",
    Cor: "Preto",
    Ano: 2020,
    Km: 25000,
    Preço: 48000,
  },
  {
    imageURL: `${carPic3}`,
    Marca: "Ford",
    Modelo: "Focus",
    Combustível: "Diesel",
    Cor: "Azul",
    Ano: 2016,
    Km: 55000,
    Preço: 35000,
  },
  {
    imageURL: `${carPic1}`,
    Marca: "Volkswagen",
    Modelo: "Golf",
    Combustível: "Gasolina",
    Cor: "Prata",
    Ano: 2019,
    Km: 18000,
    Preço: 42000,
  },
  {
    imageURL: `${carPic2}`,
    Marca: "Chevrolet",
    Modelo: "Onix",
    Combustível: "Etanol",
    Cor: "Vermelho",
    Ano: 2022,
    Km: 10000,
    Preço: 50000,
  },
  {
    imageURL: `${carPic2}`,
    Marca: "Chevrolet",
    Modelo: "Onix",
    Combustível: "Etanol",
    Cor: "Vermelho",
    Ano: 2022,
    Km: 10000,
    Preço: 50000,
  },
  {
    imageURL: `${carPic2}`,
    Marca: "Chevrolet",
    Modelo: "Onix",
    Combustível: "Etanol",
    Cor: "Vermelho",
    Ano: 2022,
    Km: 10000,
    Preço: 50000,
  },
  {
    imageURL: `${carPic3}`,
    Marca: "Nissan",
    Modelo: "Sentra",
    Combustível: "Gasolina",
    Cor: "Cinza",
    Ano: 2017,
    Km: 40000,
    Preço: 38000,
  },
  {
    imageURL: `${carPic1}`,
    Marca: "Renault",
    Modelo: "Sandero",
    Combustível: "Etanol",
    Cor: "Branco",
    Ano: 2021,
    Km: 15000,
    Preço: 42000,
  },
  {
    imageURL: `${carPic2}`,
    Marca: "Hyundai",
    Modelo: "HB20",
    Combustível: "Gasolina",
    Cor: "Prata",
    Ano: 2020,
    Km: 22000,
    Preço: 39000,
  },
  {
    imageURL: `${carPic3}`,
    Marca: "Fiat",
    Modelo: "Uno",
    Combustível: "Etanol",
    Cor: "Vermelho",
    Ano: 2015,
    Km: 60000,
    Preço: 28000,
  },
  {
    imageURL: `${carPic1}`,
    Marca: "Mitsubishi",
    Modelo: "Lancer",
    Combustível: "Gasolina",
    Cor: "Preto",
    Ano: 2014,
    Km: 70000,
    Preço: 32000,
  },
  {
    imageURL: `${carPic3}`,
    Marca: "Kia",
    Modelo: "Sportage",
    Combustível: "Diesel",
    Cor: "Branco",
    Ano: 2019,
    Km: 28000,
    Preço: 47000,
  },
  {
    imageURL: `${carPic1}`,
    Marca: "Peugeot",
    Modelo: "208",
    Combustível: "Gasolina",
    Cor: "Azul",
    Ano: 2018,
    Km: 32000,
    Preço: 38000,
  },
  {
    imageURL: `${carPic2}`,
    Marca: "Audi",
    Modelo: "A3",
    Combustível: "Etanol",
    Cor: "Prata",
    Ano: 2022,
    Km: 15000,
    Preço: 52000,
  },
  {
    imageURL: `${carPic3}`,
    Marca: "BMW",
    Modelo: "Série 3",
    Combustível: "Gasolina",
    Cor: "Preto",
    Ano: 2023,
    Km: 10000,
    Preço: 55000,
  },
  {
    imageURL: `${carPic1}`,
    Marca: "Mercedes-Benz",
    Modelo: "C-Class",
    Combustível: "Diesel",
    Cor: "Cinza",
    Ano: 2021,
    Km: 18000,
    Preço: 52000,
  },
];
