import carPic1 from "../assets/carro 1.png";
import carPic2 from "../assets/carro 2.png";
import carPic3 from "../assets/carro 3.png";

export const mockList = [
  {
    imageURL: `${carPic1}`,
    brand: "Toyota",
    model: "Corolla",
    fuel: "Gasolina",
    color: "Branco",
    year: 2018,
    kilometers: 350000,
    price: 450000,
  },
  {
    imageURL: `${carPic2}`,
    brand: "Honda",
    model: "Civic",
    fuel: "Etanol",
    color: "Preto",
    year: 2020,
    kilometers: 25002,
    price: 48000,
  },
  {
    imageURL: `${carPic3}`,
    brand: "Ford",
    model: "Focus",
    fuel: "Diesel",
    color: "Azul",
    year: 2016,
    kilometers: 55003,
    price: 35000,
  },
  {
    imageURL: `${carPic1}`,
    brand: "Volkswagen",
    model: "Golf",
    fuel: "Gasolina",
    color: "Prata",
    year: 2019,
    kilometers: 18004,
    price: 42000,
  },
  {
    imageURL: `${carPic2}`,
    brand: "Chevrolet",
    model: "Onix",
    fuel: "Etanol",
    color: "Vermelho",
    year: 2022,
    kilometers: 10005,
    price: 50000,
  },
  {
    imageURL: `${carPic2}`,
    brand: "Chevrolet",
    model: "Onix",
    fuel: "Etanol",
    color: "Vermelho",
    year: 2022,
    kilometers: 10006,
    price: 50000,
  },
  {
    imageURL: `${carPic2}`,
    brand: "Chevrolet",
    model: "Onix",
    fuel: "Etanol",
    color: "Vermelho",
    year: 2022,
    kilometers: 10007,
    price: 50000,
  },
  {
    imageURL: `${carPic3}`,
    brand: "Nissan",
    model: "Sentra",
    fuel: "Gasolina",
    color: "Cinza",
    year: 2017,
    kilometers: 40008,
    price: 38000,
  },
  {
    imageURL: `${carPic1}`,
    brand: "Renault",
    model: "Sandero",
    fuel: "Etanol",
    color: "Branco",
    year: 2021,
    kilometers: 15009,
    price: 42000,
  },
  {
    imageURL: `${carPic2}`,
    brand: "Hyundai",
    model: "HB20",
    fuel: "Gasolina",
    color: "Prata",
    year: 2020,
    kilometers: 22002,
    price: 39000,
  },
  {
    imageURL: `${carPic3}`,
    brand: "Fiat",
    model: "Uno",
    fuel: "Etanol",
    color: "Vermelho",
    year: 2015,
    kilometers: 60004,
    price: 28000,
  },
  {
    imageURL: `${carPic1}`,
    brand: "Mitsubishi",
    model: "Lancer",
    fuel: "Gasolina",
    color: "Preto",
    year: 2014,
    kilometers: 70045,
    price: 32000,
  },
];
